### ISSUE TITLE
Unable to connect to Essbase

### ISSUE THREAD

**Issue by JagadishRaoPES** [jasonwjones/essbasepy#4]
Hello,

I am unable to execute below command post importing Essbase module. Any help would be great. Thank you!

<img width="924" alt="screen shot 2016-06-16 at 8 19 39 pm" src="https://cloud.githubusercontent.com/assets/19977631/16121174/e1b56a7e-33ff-11e6-9bfc-b336d827cbad.png">

**Comment by jasonwjones** [comment]
Did you happen to import the “ctypes” module? This should be done with “import ctypes”. I haven’t worked on this in awhile but it looks like that needs to happen.

Thanks,

--
Jason Jones
http://www.linkedin.com/in/jaswjones
jason@saxifrages.com | Saxifrage Systems LLC
206-227-5719


On June 16, 2016 at 7:51:54 AM, JagadishRaoPES (notifications@github.com) wrote:

Hello,

I am unable to execute below command post importing Essbase module. Any help would be great. Thank you!

**Comment by nurzen** [comment]
Hello,

maybe there is a problem with the enviroment variables. Because ctypes indicates symbol not found, that means the function MaxlInit was not availabe. Please check ESSBASEPATH and PATH.

In my case its
ESSBASEPATH=C:\Oracle\Middleware\EPMSystem11R1\common\EssbaseRTC-64\11.1.2.0
PATH=C:\Oracle\Middleware\EPMSystem11R1\common\EssbaseRTC-64\11.1.2.0\bin;C:\Oracle\Middleware\EPMSystem11R1\bin;

You could also check if you can run essmsh.

Good Luck
Kevin

**Comment by Naveen-Suram** [comment]
Even I am getting the same error. Any solution to this problem?

Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import Essbase
>>> import ctypes
>>> esb = Essbase.Essbase()
Using Maxl DLL in D:\Oracle\Middleware\EPMSystem11R1\common\EssbaseRTC-64\11.1.2.0\bin\essmaxlu.dll
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    esb = Essbase.Essbase()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\Essbase.py", line 184, in __init__
    if "11.1.2.4" in (getFileVerInfo(__maxldll)):
TypeError: a bytes-like object is required, not 'str'

ESSMSH is working fine:

C:\Users\naveen.suram>essmsh

 Essbase MaxL Shell 64-bit - Release 11.1.2 (ESB11.1.2.4.000B193)
 Copyright (c) 2000, 2015, Oracle and/or its affiliates.
 All rights reserved.

MAXL>

**Comment by nurzen** [comment]
The check compares a string "11.1.2.4" with a bytes object (string in python 3.6)
change the line to
if b"11.1.2.4" in (getFileVerInfo(__maxldll)):

already made that change in my branch and send a pull request to jason.

**Comment by Naveen-Suram** [comment]
Many thanks. Post changing the code, its working now.

**Comment by ExGnyaana** [comment]
I am getting this error when i try to execute Maxl. Till connection it goes fine. Problem is when i execute it:

**>  "Execution of [display application FDSETL;] failed with status 110"**

My code:
```
import Essbase
esb=Essbase.Essbase()
esb.connect('username','password',host=localhost')
esb.execute("display application;") # Problem is from this line
```

If i try the same in essmsh.exe, it works perfectly fine!!!

Please help
@nurzen @jasonwjones

**Comment by ExGnyaana** [comment]
I am getting this error when i try to execute Maxl. Till connection it goes fine. Problem is when i execute it:

**>  "Execution of [display application;] failed with status 110"**

My code:
```
import Essbase
esb=Essbase.Essbase()
esb.connect('username','password',host=localhost')
esb.execute("display application;") # Problem is from this line
```

If i try the same in essmsh.exe, it works perfectly fine!!!

Please help
@nurzen @jasonwjones

**Comment by nurzen** [comment]
Hello,
i think the semi-colon at the end causes the error. 
Try
esb.execute("display application")

**Comment by ExGnyaana** [comment]
Tried your suggestion, but still the same error. Am attaching the screenshot.

![image](https://user-images.githubusercontent.com/60724243/74142181-59f24180-4c1e-11ea-8712-44267ea7e509.png)

**Comment by nurzen** [comment]
can you see the connection (before the display application) in the administration services console?

**Comment by ExGnyaana** [comment]
First screenshot is Essbase connection through Essmsh.exe, Second screenshot is Python. I checked the connection in EAS, it works.

**ESSMSH >>>**
![image](https://user-images.githubusercontent.com/60724243/74152663-ced07600-4c34-11ea-8797-6d0ec92d1205.png)


**Python >>>>**

We can see Python jumping to the next line after esb.connect. So, it has executed the connection line successfully.  I have highlighted that in red.
![image](https://user-images.githubusercontent.com/60724243/74152771-04755f00-4c35-11ea-9ed6-4facf43ff49a.png)

**Comment by nurzen** [comment]
Sorry, cant reproduce the Error.
Found a knowledge base article for the error maybe you can try this
https://support.oracle.com/knowledge/Enterprise%20Performance%20Management%20and%20Business%20Intelligence/1498864_1.html

**Comment by 15Ram** [comment]
Hello,
I need a help to run Essbase in Python

I am trying to run same commands as above and i get some error

Commands trying to run in cmd:
import Essbase

Error:
Traceback <most recent call last>:
file "<stdin>",line1,in <module>

When i run the essmsh i get
Essbase MAXL shell 64-bit Release 11.1.2<ESB 11.1.2.4.>

**Comment by ghost** [comment]
can you give us screen shot ?

**Comment by 15Ram** [comment]
Thanks,


![image](https://user-images.githubusercontent.com/64909641/81214205-6a247d80-8fcf-11ea-9fed-dc3c35490daf.png)

**Comment by nurzen** [comment]
python cant find the module. You have to put the Essbase.py file in your working directory or put it under Lib\site-packages of your python installation.

**Comment by osnnsrhy** [comment]
Hi,
For esb.connect, I put my username and password for essbase.

But for the host=' ' How can I know what the host name/server name and port is? If the server is https, what is the format there? Trying to connect to the cube in essbase. I've putting the https server name there, but nothing seems to connect when I try to execute

Pretty new to this stuff, so any help is greatly appreciated.

**Comment by nurzen** [comment]
Hello,
you only need the name of the server which is running essbase no https or so in front. I think the DLL is using the agent Port which is per default 1423.
https://docs.oracle.com/cd/E57185_01/EASOH/essports.html

**Comment by osnnsrhy** [comment]
Hi, thank you for your response.
I am still getting an error - 1030818 - login failed. Please check if server and port are correct.

Is there a way for me to check the essbase server name and the port? Perhaps I am not inputting the correct server name.

**Comment by osnnsrhy** [comment]
The error I have now is:

Error 1040048 - HTTP communication failed with error [peer certificate cannot be authenticated with given CA certificates].

I was trying to login through the maxl shell with the format here:
https://docs.oracle.com/cd/E57185_01/ESBTR/maxl_invoke_login.html

Using the second example on the website above.
Any input is appreciated.

**Comment by nurzen** [comment]
Hello,
so you are connecting through aps (analytic provider services) which is another product. please try first connecting to the server directly as in the first example.

**Comment by osnnsrhy** [comment]
Hi again,
Thank you for the response, I have tried logging into the server through maxl shell, but still, I am unable to connect.
Below is what I typed in to the maxl shell:
Login <username> <pw> on <server>;

I get errors, unable to retrieve host information, and login failed, please check if server and port are correct.

I believe it is through aps, does this not support connections through aps? If it does, how can I login?
